# Generated by Django 4.0.4 on 2022-05-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ativo',
        ),
        migrations.AddField(
            model_name='comment',
            name='comentario_aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
